[package]
name = "noten"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
toml = "0.4.1"
quick-error = "1.1"
log = "0.3.5"
env_logger = "0.4"
regex = "0.2"
hoedown = "6"
lazy_static = "0.2.0"
serde = "1.0.7"
serde_derive = "1.0.7"
