[package]
name = "noten"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
toml = "0.5.6"
quick-error = "1.2.3"
log = "0.4.8"
env_logger = "0.7.1"
regex = "1.3.9"
hoedown = "6.0.0"
lazy_static = "1.4.0"
serde = "1.0.111"
serde_derive = "1.0.111"
