[package]
name = "noten"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
toml = "0.5.7"
quick-error = "2.0.0"
log = "0.4.11"
env_logger = "0.8.2"
regex = "1.4.2"
hoedown = "6.0.0"
lazy_static = "1.4.0"
serde = "1.0.118"
serde_derive = "1.0.118"
