[package]
name = "noten"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
toml = "0.5.9"
quick-error = "2.0.1"
log = "0.4.17"
env_logger = "0.9.0"
regex = "1.6.0"
hoedown = "6.0.0"
lazy_static = "1.4.0"
serde = "1.0.139"
serde_derive = "1.0.139"
